# Generated by Django 5.1.6 on 2025-02-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDB',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('imgurl', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'usersdb',
            },
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('watch', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'userstats',
            },
        ),
    ]
